#ifndef _BXDF_TEXTURE_DEF_H_
#define _BXDF_TEXTURE_DEF_H_

#define BXDFTEX_BRDF_SIZE_X 32
#define BXDFTEX_BRDF_SIZE_Y 32

#define BXDFTEX_BRDF_DIELECTRIC_SIZE_X 32
#define BXDFTEX_BRDF_DIELECTRIC_SIZE_Y 16
#define BXDFTEX_BRDF_DIELECTRIC_SIZE_Z 16

#endif