#ifndef _SUM_LUMINANCE_DEF_H_
#define _SUM_LUMINANCE_DEF_H_

#define SL_BLOCKSIZE  8
#define SL_BLOCKSIZEY 8
#define SL_REDUCE_TO_1D_GROUPTHREADS ( BLOCKSIZE * BLOCKSIZEY )
#define SL_REDUCE_TO_SINGLE_GROUPTHREADS 128

#endif